packages:
  - "server"
  - "desktop"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  electron: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - autoprefixer@10.5.2
